export const FORM_HANDLER = 'FORM_HANDLER';
export const FORM_HANDLER_CLEAR = 'FORM_HANDLER_CLEAR';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";